steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/chimera/fsu6-lay-intelligence:$COMMIT_SHA', '-t', 'gcr.io/chimera/fsu6-lay-intelligence:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/chimera/fsu6-lay-intelligence:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/chimera/fsu6-lay-intelligence:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fsu6-lay-intelligence
      - '--image=gcr.io/chimera/fsu6-lay-intelligence:$COMMIT_SHA'
      - '--region=europe-west2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--timeout=60'
      - '--service-account=fsu6-lay-intelligence@chimera.iam.gserviceaccount.com'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=chimera'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'services', 'update-traffic', 'fsu6-lay-intelligence', '--region=europe-west2', '--to-latest']

images:
  - 'gcr.io/chimera/fsu6-lay-intelligence:$COMMIT_SHA'
  - 'gcr.io/chimera/fsu6-lay-intelligence:latest'

options:
  logging: CLOUD_LOGGING_ONLY
